// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chatService.proto

#include "chatService.pb.h"
#include "chatService.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chatservice {

static const char* ChatService_method_names[] = {
  "/chatservice.ChatService/CreateAccount",
  "/chatservice.ChatService/Login",
  "/chatservice.ChatService/Logout",
  "/chatservice.ChatService/ListUsers",
  "/chatservice.ChatService/SendMessage",
  "/chatservice.ChatService/QueryNotifications",
  "/chatservice.ChatService/QueryMessages",
  "/chatservice.ChatService/DeleteAccount",
  "/chatservice.ChatService/MessagesSeen",
  "/chatservice.ChatService/NewMessage",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateAccount_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Login_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Logout_(ChatService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListUsers_(ChatService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SendMessage_(ChatService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryNotifications_(ChatService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_QueryMessages_(ChatService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_DeleteAccount_(ChatService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_MessagesSeen_(ChatService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NewMessage_(ChatService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatService::Stub::CreateAccount(::grpc::ClientContext* context, const ::chatservice::createAccountMessage& request, ::chatservice::createAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::createAccountMessage, ::chatservice::createAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAccount_, context, request, response);
}

void ChatService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::chatservice::createAccountMessage* request, ::chatservice::createAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::createAccountMessage, ::chatservice::createAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, std::move(f));
}

void ChatService::Stub::async::CreateAccount(::grpc::ClientContext* context, const ::chatservice::createAccountMessage* request, ::chatservice::createAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::createAccountReply>* ChatService::Stub::PrepareAsyncCreateAccountRaw(::grpc::ClientContext* context, const ::chatservice::createAccountMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::createAccountReply, ::chatservice::createAccountMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::createAccountReply>* ChatService::Stub::AsyncCreateAccountRaw(::grpc::ClientContext* context, const ::chatservice::createAccountMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::Login(::grpc::ClientContext* context, const ::chatservice::loginMessage& request, ::chatservice::loginReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::loginMessage, ::chatservice::loginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void ChatService::Stub::async::Login(::grpc::ClientContext* context, const ::chatservice::loginMessage* request, ::chatservice::loginReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::loginMessage, ::chatservice::loginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Login(::grpc::ClientContext* context, const ::chatservice::loginMessage* request, ::chatservice::loginReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::loginReply>* ChatService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::chatservice::loginMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::loginReply, ::chatservice::loginMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::loginReply>* ChatService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::chatservice::loginMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::Logout(::grpc::ClientContext* context, const ::chatservice::logoutMessage& request, ::chatservice::logoutReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::logoutMessage, ::chatservice::logoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Logout_, context, request, response);
}

void ChatService::Stub::async::Logout(::grpc::ClientContext* context, const ::chatservice::logoutMessage* request, ::chatservice::logoutReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::logoutMessage, ::chatservice::logoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Logout(::grpc::ClientContext* context, const ::chatservice::logoutMessage* request, ::chatservice::logoutReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::logoutReply>* ChatService::Stub::PrepareAsyncLogoutRaw(::grpc::ClientContext* context, const ::chatservice::logoutMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::logoutReply, ::chatservice::logoutMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Logout_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::logoutReply>* ChatService::Stub::AsyncLogoutRaw(::grpc::ClientContext* context, const ::chatservice::logoutMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLogoutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chatservice::user>* ChatService::Stub::ListUsersRaw(::grpc::ClientContext* context, const ::chatservice::queryUsersMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::user>::Create(channel_.get(), rpcmethod_ListUsers_, context, request);
}

void ChatService::Stub::async::ListUsers(::grpc::ClientContext* context, const ::chatservice::queryUsersMessage* request, ::grpc::ClientReadReactor< ::chatservice::user>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::user>::Create(stub_->channel_.get(), stub_->rpcmethod_ListUsers_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::user>* ChatService::Stub::AsyncListUsersRaw(::grpc::ClientContext* context, const ::chatservice::queryUsersMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::user>::Create(channel_.get(), cq, rpcmethod_ListUsers_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::user>* ChatService::Stub::PrepareAsyncListUsersRaw(::grpc::ClientContext* context, const ::chatservice::queryUsersMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::user>::Create(channel_.get(), cq, rpcmethod_ListUsers_, context, request, false, nullptr);
}

::grpc::Status ChatService::Stub::SendMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::chatservice::sendMessageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::chatMessage, ::chatservice::sendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage* request, ::chatservice::sendMessageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::chatMessage, ::chatservice::sendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void ChatService::Stub::async::SendMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage* request, ::chatservice::sendMessageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::sendMessageReply>* ChatService::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::sendMessageReply, ::chatservice::chatMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::sendMessageReply>* ChatService::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chatservice::notification>* ChatService::Stub::QueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::queryNotificationsMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::notification>::Create(channel_.get(), rpcmethod_QueryNotifications_, context, request);
}

void ChatService::Stub::async::QueryNotifications(::grpc::ClientContext* context, const ::chatservice::queryNotificationsMessage* request, ::grpc::ClientReadReactor< ::chatservice::notification>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::notification>::Create(stub_->channel_.get(), stub_->rpcmethod_QueryNotifications_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::notification>* ChatService::Stub::AsyncQueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::queryNotificationsMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::notification>::Create(channel_.get(), cq, rpcmethod_QueryNotifications_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::notification>* ChatService::Stub::PrepareAsyncQueryNotificationsRaw(::grpc::ClientContext* context, const ::chatservice::queryNotificationsMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::notification>::Create(channel_.get(), cq, rpcmethod_QueryNotifications_, context, request, false, nullptr);
}

::grpc::ClientReader< ::chatservice::chatMessage>* ChatService::Stub::QueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::queryMessagesMessage& request) {
  return ::grpc::internal::ClientReaderFactory< ::chatservice::chatMessage>::Create(channel_.get(), rpcmethod_QueryMessages_, context, request);
}

void ChatService::Stub::async::QueryMessages(::grpc::ClientContext* context, const ::chatservice::queryMessagesMessage* request, ::grpc::ClientReadReactor< ::chatservice::chatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chatservice::chatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_QueryMessages_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chatservice::chatMessage>* ChatService::Stub::AsyncQueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::queryMessagesMessage& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::chatMessage>::Create(channel_.get(), cq, rpcmethod_QueryMessages_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chatservice::chatMessage>* ChatService::Stub::PrepareAsyncQueryMessagesRaw(::grpc::ClientContext* context, const ::chatservice::queryMessagesMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chatservice::chatMessage>::Create(channel_.get(), cq, rpcmethod_QueryMessages_, context, request, false, nullptr);
}

::grpc::Status ChatService::Stub::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::deleteAccountMessage& request, ::chatservice::deleteAccountReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::deleteAccountMessage, ::chatservice::deleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteAccount_, context, request, response);
}

void ChatService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::deleteAccountMessage* request, ::chatservice::deleteAccountReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::deleteAccountMessage, ::chatservice::deleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, std::move(f));
}

void ChatService::Stub::async::DeleteAccount(::grpc::ClientContext* context, const ::chatservice::deleteAccountMessage* request, ::chatservice::deleteAccountReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::deleteAccountReply>* ChatService::Stub::PrepareAsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::chatservice::deleteAccountMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::deleteAccountReply, ::chatservice::deleteAccountMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::deleteAccountReply>* ChatService::Stub::AsyncDeleteAccountRaw(::grpc::ClientContext* context, const ::chatservice::deleteAccountMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::messagesSeenMessage& request, ::chatservice::messagesSeenMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::messagesSeenMessage, ::chatservice::messagesSeenMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MessagesSeen_, context, request, response);
}

void ChatService::Stub::async::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::messagesSeenMessage* request, ::chatservice::messagesSeenMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::messagesSeenMessage, ::chatservice::messagesSeenMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MessagesSeen_, context, request, response, std::move(f));
}

void ChatService::Stub::async::MessagesSeen(::grpc::ClientContext* context, const ::chatservice::messagesSeenMessage* request, ::chatservice::messagesSeenMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MessagesSeen_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::messagesSeenMessage>* ChatService::Stub::PrepareAsyncMessagesSeenRaw(::grpc::ClientContext* context, const ::chatservice::messagesSeenMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::messagesSeenMessage, ::chatservice::messagesSeenMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MessagesSeen_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::messagesSeenMessage>* ChatService::Stub::AsyncMessagesSeenRaw(::grpc::ClientContext* context, const ::chatservice::messagesSeenMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMessagesSeenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatService::Stub::NewMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::chatservice::newMessageReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chatservice::chatMessage, ::chatservice::newMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NewMessage_, context, request, response);
}

void ChatService::Stub::async::NewMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage* request, ::chatservice::newMessageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chatservice::chatMessage, ::chatservice::newMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewMessage_, context, request, response, std::move(f));
}

void ChatService::Stub::async::NewMessage(::grpc::ClientContext* context, const ::chatservice::chatMessage* request, ::chatservice::newMessageReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chatservice::newMessageReply>* ChatService::Stub::PrepareAsyncNewMessageRaw(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chatservice::newMessageReply, ::chatservice::chatMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NewMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chatservice::newMessageReply>* ChatService::Stub::AsyncNewMessageRaw(::grpc::ClientContext* context, const ::chatservice::chatMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNewMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::createAccountMessage, ::chatservice::createAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::createAccountMessage* req,
             ::chatservice::createAccountReply* resp) {
               return service->CreateAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::loginMessage, ::chatservice::loginReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::loginMessage* req,
             ::chatservice::loginReply* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::logoutMessage, ::chatservice::logoutReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::logoutMessage* req,
             ::chatservice::logoutReply* resp) {
               return service->Logout(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::queryUsersMessage, ::chatservice::user>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::queryUsersMessage* req,
             ::grpc::ServerWriter<::chatservice::user>* writer) {
               return service->ListUsers(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::chatMessage, ::chatservice::sendMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::chatMessage* req,
             ::chatservice::sendMessageReply* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[5],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::queryNotificationsMessage, ::chatservice::notification>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::queryNotificationsMessage* req,
             ::grpc::ServerWriter<::chatservice::notification>* writer) {
               return service->QueryNotifications(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chatservice::queryMessagesMessage, ::chatservice::chatMessage>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::queryMessagesMessage* req,
             ::grpc::ServerWriter<::chatservice::chatMessage>* writer) {
               return service->QueryMessages(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::deleteAccountMessage, ::chatservice::deleteAccountReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::deleteAccountMessage* req,
             ::chatservice::deleteAccountReply* resp) {
               return service->DeleteAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::messagesSeenMessage, ::chatservice::messagesSeenMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::messagesSeenMessage* req,
             ::chatservice::messagesSeenMessage* resp) {
               return service->MessagesSeen(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chatservice::chatMessage, ::chatservice::newMessageReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chatservice::chatMessage* req,
             ::chatservice::newMessageReply* resp) {
               return service->NewMessage(ctx, req, resp);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::CreateAccount(::grpc::ServerContext* context, const ::chatservice::createAccountMessage* request, ::chatservice::createAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Login(::grpc::ServerContext* context, const ::chatservice::loginMessage* request, ::chatservice::loginReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::Logout(::grpc::ServerContext* context, const ::chatservice::logoutMessage* request, ::chatservice::logoutReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::ListUsers(::grpc::ServerContext* context, const ::chatservice::queryUsersMessage* request, ::grpc::ServerWriter< ::chatservice::user>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::SendMessage(::grpc::ServerContext* context, const ::chatservice::chatMessage* request, ::chatservice::sendMessageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::QueryNotifications(::grpc::ServerContext* context, const ::chatservice::queryNotificationsMessage* request, ::grpc::ServerWriter< ::chatservice::notification>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::QueryMessages(::grpc::ServerContext* context, const ::chatservice::queryMessagesMessage* request, ::grpc::ServerWriter< ::chatservice::chatMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::DeleteAccount(::grpc::ServerContext* context, const ::chatservice::deleteAccountMessage* request, ::chatservice::deleteAccountReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::MessagesSeen(::grpc::ServerContext* context, const ::chatservice::messagesSeenMessage* request, ::chatservice::messagesSeenMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::NewMessage(::grpc::ServerContext* context, const ::chatservice::chatMessage* request, ::chatservice::newMessageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chatservice

